### ISSUE TITLE
Sublime Text 3 Compatibility

### ISSUE THREAD

**Issue by codemakerlive** [filcab/SublimeLLDB#7]
Would you consider upgrading the package support to ST3?

**Comment by wizza-smile** [comment]
:+1:

**Comment by Falven** [comment]
Agreed, but has anyone tried it with 3 yet?

**Comment by theqlabs** [comment]
Without doing much digging into why, it looks like SublimeLLDB loads fine on ST2 but not ST3 (as of Build 3083)

**Comment by filcab** [comment]
I'm sorry for not replying earlier.
I have no plans on updating this to work for SublimeText 3. I'm not using that text editor any more.

I'm going to tag this as abandonned, but feel free to ask about anything should anyone attempt to port it and need help.
